services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: https://backend.deneme1.blitz.cloud
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
