'use client';
import {ResponsiveContainer,AreaChart,Area,CartesianGrid,XAxis,YAxis,Tooltip,LineChart,Line,BarChart,Bar,ReferenceLine} from 'recharts';
import type {Point,Candle,Signal} from '../app/types';
const axis={fill:'#8b96aa',fontSize:12};
export function EquityChart({data,field='equity'}:{data:Point[];field?:'equity'|'pnl'|'drawdown'}){return <div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id={'fill'+field} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={field==='drawdown'?'#ff4d67':'#00c896'} stopOpacity={.25}/><stop offset="100%" stopColor="#00c896" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#202835" vertical={false}/><XAxis dataKey="date" tick={axis} minTickGap={60} tickLine={false}/><YAxis domain={['auto','auto']} tick={axis} tickFormatter={v=>Number(v).toLocaleString('tr-TR',{maximumFractionDigits:0})} width={72} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#151d29',border:'1px solid #303b4c',color:'#eee'}}/><Area type="linear" dataKey={field} name={field==='equity'?'Portföy':field==='pnl'?'Günlük K/Z':'Drawdown %'} stroke={field==='drawdown'?'#ff4d67':'#00c896'} fill={`url(#fill${field})`} strokeWidth={2} isAnimationActive={false}/></AreaChart></ResponsiveContainer></div>}
export function CandleChart({data,signal}:{data:Candle[];signal:Signal}){
 const bars=data.slice(-55);const min=Math.min(...bars.map(x=>x.low),signal.stop)*.985;const max=Math.max(...bars.map(x=>x.high),signal.target2)*1.015; const y=(v:number)=>280-(v-min)/(max-min)*250;const x=(i:number)=>55+i*12;
 return <div className="candles"><svg viewBox="0 0 760 325" role="img" aria-label="Sentetik günlük mum grafiği ve EMA seviyeleri">{[0,1,2,3,4].map(i=><g key={i}><line x1="48" x2="720" y1={30+i*62.5} y2={30+i*62.5} stroke="#26303d"/><text x="4" y={34+i*62.5} fill="#8996aa" fontSize="12">{(max-(max-min)*i/4).toFixed(1)}</text></g>)}{bars.map((b,i)=><g key={b.date}><title>{b.date}: A {b.open.toFixed(2)} Y {b.high.toFixed(2)} D {b.low.toFixed(2)} K {b.close.toFixed(2)}</title><line x1={x(i)} x2={x(i)} y1={y(b.high)} y2={y(b.low)} stroke={b.close>=b.open?'#00c896':'#ff4d67'}/><rect x={x(i)-3} width="6" y={Math.min(y(b.open),y(b.close))} height={Math.max(1,Math.abs(y(b.open)-y(b.close)))} fill={b.close>=b.open?'#00c896':'#ff4d67'}/></g>)}{(['ema20','ema50','ema200'] as const).map((key,i)=><polyline key={key} points={bars.map((b,j)=>`${x(j)},${y(b[key])}`).join(' ')} fill="none" stroke={['#4f8cff','#e4b95d','#b995ef'][i]} strokeWidth="1.4"/>)}{[['Stop',signal.stop,'#ff4d67'],['Hedef 1',signal.target1,'#00c896'],['Hedef 2',signal.target2,'#00c896'],['Giriş',signal.entry,'#4f8cff'],['Destek',bars.at(-1)?.support||signal.stop,'#a5b1c3'],['Direnç',bars.at(-1)?.resistance||signal.target1,'#a5b1c3']] .map(([label,value,color])=><g key={label}><line x1="48" x2="720" y1={y(Number(value))} y2={y(Number(value))} stroke={String(color)} strokeDasharray="4 5"/><text x="625" y={y(Number(value))-5} fill={String(color)} fontSize="12">{label}</text></g>)}<text x="50" y="315" fill="#8996aa" fontSize="12">{bars[0]?.date}</text><text x="620" y="315" fill="#8996aa" fontSize="12">{bars.at(-1)?.date}</text></svg><div className="legend">● <span>EMA 20</span><span style={{color:'#e4b95d'}}>● EMA 50</span><span style={{color:'#b995ef'}}>● EMA 200</span></div></div>
}
export function IndicatorChart({data,kind}:{data:Candle[];kind:'rsi'|'macd'|'volume'}){return <div style={{height:150}}><ResponsiveContainer width="100%" height="100%">{kind==='volume'?<BarChart data={data}><XAxis dataKey="date" hide/><YAxis hide/><Tooltip/><Bar dataKey="volume" fill="#344e73"/></BarChart>:<LineChart data={data}><XAxis dataKey="date" hide/><YAxis tick={axis} domain={kind==='rsi'?[0,100]:['auto','auto']} width={45}/><Tooltip contentStyle={{background:'#151d29'}}/><Line dataKey={kind} stroke="#4f8cff" dot={false}/>{kind==='rsi'?<><ReferenceLine y={70} stroke="#ff4d67" strokeDasharray="4 4"/><ReferenceLine y={30} stroke="#00c896" strokeDasharray="4 4"/></>:<Line dataKey="macd_signal" stroke="#e4b95d" dot={false}/>}</LineChart>}</ResponsiveContainer></div>}
